apiVersion: v1
kind: Secret
metadata:
  name: dev-tools-secrets
  namespace: dev-tools-portal
type: Opaque
stringData:
  MONGODB_URI: mongodb://mongo:27017/dev-tools-portal
  JWT_SECRET: a5d4eb3bf00a074d834bf57672a87320094a2e39f14810759a1c5282bea29e49
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin123
